/* eslint-disable no-shadow */

/**
 * Collision groups for filtering.
 */
export const enum Groups {
  BODYGROUP_NONE = 0,
  BODYGROUP_DYNAMIC = 1,
  BODYGROUP_STATIC = 2,
  BODYGROUP_KINEMATIC = 4,
  BODYGROUP_ENGINE_1 = 8,
  BODYGROUP_TRIGGER = 16,
  BODYGROUP_ENGINE_2 = 32,
  BODYGROUP_ENGINE_3 = 64,
  BODYGROUP_USER_1 = 128,
  BODYGROUP_USER_2 = 256,
  BODYGROUP_USER_3 = 512,
  BODYGROUP_USER_4 = 1024,
  BODYGROUP_USER_5 = 2048,
  BODYGROUP_USER_6 = 4096,
  BODYGROUP_USER_7 = 8192,
  BODYGROUP_USER_8 = 16384,
}
